### PR TITLE
Conditional Forwarding DNS fix

### PR DESCRIPTION
**Pull request by boostchicken**
Conditional Forwarding now works in all DNS resolvers

### CODE REVIEW

**Comment by SturdyErde** [comment]
Double checking for my sake on this one. The code comments say "point to your router" but isn't 10.0.5.1 the gateway IP for the CNI network that you made? Or, in my case: the router is 192.168.1.1 and my CNI "DNS" network is 192.168.5.0/24. So I would expect to put my router's IP address. Would that be correct?

**Comment by mojo333** [comment]
Thanks for coming back to me.

I tried all three options (my router, the new CNI network and “dns-discovery” option removed (which should use DHCP)). My router is 192.168.200.1 and the CNI network I created is as per your example so 10.0.5.1/24 (the gateway) and 10.0.5.3 for DNS.

According to the NextDns documentation (https://github.com/nextdns/nextdns/blob/master/config/config.go)...

"The address of a DNS server to be used to discover client names.\n"+
                                                "If not defined, the address learned via DHCP will be used. This setting\n"+
                                                "is only active if report-client-info is set to true."

So I should really leave it blank as I have 4 subnets and 4 DHCP servers (one for each).

It seems that all my DNS requests (sent to 10.0.5.3:53) are somehow being rerouted to 127.0.0.1:53 (which then uses my WAN DNS (Cloudflare) which is just flooring me as even undoing all the config, deleting the container and pulling it again, doesn’t fix the issue.

I was trying to think back to when it stopped working and strangely enough it was when I was trying to route a particular laptop to my guest network (you’ll remember the issue I had with that...) As soon as I put that config in I got the error on NextDNS saying I was using Cloudflare and then undoing all changes hasn’t solved that problem... all my subnets are pointing to 10.0.5.3 for DNS but all are being resolved by Cloudflare instead of NextDns.

**Comment by SturdyErde** [comment]
Did you modify the "DHCP Name Server" setting on each of your VLANs in your UDM? 

**eg:**
image

**Comment by mojo333** [comment]
Yup, that is unchanged – all set to 10.0.5.3 as it was previously – all my VLANs and core LAN point to 10.0.5.3. As an example from my main desktop...

C:\>nslookup bbc.com
Server:  UnKnown
Address:  10.0.5.3

Non-authoritative answer:
Name:    bbc.com
Addresses:  2a04:4e42:600::81
          2a04:4e42:400::81
          2a04:4e42::81
          2a04:4e42:200::81
          151.101.0.81
          151.101.64.81
          151.101.192.81
          151.101.128.81

Looking in the NextDNS logs there are no entries for bbc.com (or any other entries for that matter)  and looking at the NextDNS home page it says I am using “Cloudflare” as my DNS provider; which is my default WAN DNS provider. There are zero entries in the nextdns log, apart from startup info I.e. this is all I see (and I have log-entries enabled for nextdns).

# podman container logs nextdns
INFO: 10:44:57 Starting NextDNS 1.7.1/linux on localhost:53
INFO: 10:44:57 Listening on TCP/127.0.0.1:53
INFO: 10:44:57 Listening on UDP/127.0.0.1:53

The only changes I made where to 10-dns.sh and nextdns.conf to update as per your “Conditional Fix (#27)”. Prior to this change everything was working perfectly, apart from Conditional Forwarding using MAC address which was talked about previously. I though this fix (#27) would resolve it so I update 10-dns.sh and nextdns.conf and now really wish I hadn’t as I cannot fix this issue at all even after going back to the most basic of configs for both (see my last post here: https://github.com/boostchicken/udm-utilities/issues/28)

Others are having exactly the same issue as me but using PiHole – I.e. no traffic going to PiHole, just to their default WAN DNS provider (https://github.com/boostchicken/udm-utilities/issues)

I have no idea how to debug this... somehow queries to 10.0.5.3:53 are being forwarded in the nextdns container to 127.0.0.1:53 which then resolves to my WAN DNS provider. I can forward a request through to NextDNS by SSH onto my UDM and run the command “nslookup bbc.com 10.0.5.3” and this will show up in the logs and on the nextdns dashboard (coming from local IP address 10.0.5.1).

**Pull request merged**
