### PR TITLE
Some build and package improvements

### PR DESCRIPTION
**Pull request by spali**
Have done some build and package improvements.
Hope you like it.
Tested it as you did with Ubuntu 20 with WSL2.
Last commit includes even support for building in docker or podman. 
I had in mind to potentially in the future build on the UDM itself which in theory could already work with these changes... but not tested yet.

Let me know if I should change something you not agree, of if a specific change need's more explanation.
i.e. the version number of the package... removed the "-1" behind, because this package is a native debian package, which means has it's own sources included.

Next plan is to support the external disk in the UDMP #43 .
I also play with the idea to use systemd in a "controller"-container and only start this container with this package.
This would allow to not only use scripts that get started, we could put systemd service files inside boot.d or similar to have the full control an flexibility of a systemd service like schedule, logs etc. For each container or just for simple scripts, including dependencies etc.
But not a systemd expert yet... so needs some research first.

### CODE REVIEW

**Comment by spali** [comment]
e77d038 makes the installation a lot less verbose but still get the output of the ssh command (which would be supressed when -q would be used)
```
root@UDMP:/# dpkg -i /data/udm-boot_1.0.2_all.deb
Selecting previously unselected package udm-boot.
(Reading database ... 64884 files and directories currently installed.)
Preparing to unpack /data/udm-boot_1.0.2_all.deb ...
Unpacking udm-boot (1.0.2) ...
Setting up udm-boot (1.0.2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/udm-boot.service → /lib/systemd/system/udm-boot.service.
#-> ubnt-dpkg-cache install
udm-boot: action=install, package=/data/dpkg-cache/stretch/packages/udm-boot_1.0.2_all.deb mark=manual
<-# ubnt-dpkg-cache install
```

**Comment by boostchicken** [comment]
@spali dont have time to test this atm, would love to merge it.  Do you have nay more test evidence or are you confident it works.

Also, can you add support for cron files and  bump the version to 1.1.0

**Comment by spali** [comment]
Currently have not more evidence, I'm confident it works, but maybe someone else has time to prove that just to be sure.
I will also add the readme changes to the new package to this pull request.

**Comment by spali** [comment]
> Also, can you add support for cron files and  bump the version to 1.1.0

I first thought about using systemd in a container that manages all the custom services or scripts. But you will anyway have to use the ssh_proxy to start everything one level heigher.
With this approach, I don't see an advantage to have an own systemd container, we could just use the already existing systemd process of the unifi-os container. 
Except someone has an idea without every systemd unit file has to call the ssh_proxy.
I don't know a simple way to execute automatically everything through the ssh_proxy.
Ideas would be welcome 🤠

**Comment by spali** [comment]
just made a issue to discuss the "service management" topic independent from this.
#46

**Pull request merged**
