### PR TITLE
Update steps to include bridge creation confirmation

### PR DESCRIPTION
**Pull request by poldim**
The script failed for me when I initially ran it and needed to reprovision the UDM. Hopefully, this saves someone else the headache of the script failing.

### CODE REVIEW

**Review by SturdyErde — COMMENTED** [review]
Nice tip, with one suggestion: since people with varied levels of knowledge are making use of this repo, it would be worth explaining what to look for when running the `netstat -r` command. Thanks!

**Comment by boostchicken** [comment]
@poldim could you resolve the conflicts?

**Comment by poldim** [comment]
@boostchicken Done

**Comment by duffenterprises** [comment]
@poldim Thanks for the tip!

**Pull request merged**
